### ISSUE TITLE
Bild in Aufgaben-Detail-Seite

### ISSUE THREAD

**Issue by luisafuss** [Mavv3006/mathbase#36]
Beim öffnen der Aufgaben-Detail-Seite wird folgender Fehler geworfen:
`Notice: Undefined index: picture in C:\Users\Luisa\mathbase\models\User.php on line 36`

**Comment by luisafuss** [comment]
@Mavv3006 Das ist behoben, oder? :)

**Comment by Mavv3006** [comment]
> @Mavv3006 Das ist behoben, oder? :)

Ja.
